### ISSUE TITLE
As an application submitter, I would like a way to cancel my application.

### ISSUE THREAD

**Issue by lauraGgit** [18F/forest-service-prototype#11]

**Comment by lauraGgit** [comment]
Working on in #17

**Comment by fureigh** [comment]
**Technical notes:**
- Let's have this be accessible from the edit page, presumably as a button.
- Require confirmation before canceling. I assume that we're not giving them a way to reinstate their application, at least not at first.
- New `Canceled by Applicant` (or whatever) status in `STATUS_CHOICES`.
