### ISSUE TITLE
As an application submitter, I want confirmation my application was successfully submitted (before it’s been approved).

### ISSUE THREAD

**Issue by lauraGgit** [18F/forest-service-prototype#13]

**Comment by lauraGgit** [comment]
I'm going to start adding in the confirmation page details.

**Comment by colinpmacarthur** [comment]
Sounds great, @lauraGgit. Keep me in the loop on your progress; I can either sketch or give thoughts based on what you have, by the time I get to it.

Colin

**Comment by lauraGgit** [comment]
I have an uncommitted update on this. you can probably hold off on a sketch
until I push that out.
