### ISSUE TITLE
As a Forest Service admin, I want to see applications that need approval.

### ISSUE THREAD

**Issue by fureigh** [18F/forest-service-prototype#2]
**User story:**
As a Forest Service admin, I want to see a submitted application that needs approval so that I can approve or deny it.

**Outstanding questions:**
- Are there any other possible outcomes for/states of an application? ("Needs work," for instance?)
- What happens if someone's application is denied? Simplest is probably to send them a notification and information about who to call/email for further context. Further down the road, we might want to give them their content and a chance to edit and resubmit it.

**Comment by fureigh** [comment]
Also:
- What do admins want to see at a glance, and what are they willing to click into the application for?
- What is the approval workflow? (TBD)

**Comment by lauraGgit** [comment]
Relatedly: 
- [ ] As a fs admin, I would like to change the status of a submitted application to "Approved"/"Not Approved" (https://github.com/18F/forest-service-prototype/issues/23)
- [ ] As a forest service admin, I would like to know if an application has been cancelled by the application submitter. (https://github.com/18F/forest-service-prototype/issues/24)

**Comment by fureigh** [comment]
Edited @lauraGgit's comment above to include issue numbers. :high_five:

Closing this issue because #8 was merged; I'll make additional changes in a new branch and PR.

**Comment by fureigh** [comment]
Follow-up pieces ready for review in #33.
