### ISSUE TITLE
As a forest service admin, I would like to know if an application has been cancelled by the application submitter.

### ISSUE THREAD

**Issue by lauraGgit** [18F/forest-service-prototype#24]

**Comment by fureigh** [comment]
Does the admin want a realtime update or do they just want the information to be reflected in the list of applications that do (and don't) need to be reviewed?

**Comment by lauraGgit** [comment]
I think it can be reflected in the list of applications.

Sent from my iPhone

On Sep 27, 2016, at 2:24 PM, Fureigh notifications@github.com wrote:

Does the admin want a realtime update or do they just want the information
to be reflected in the list of applications that do (and don't) need to be
reviewed?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/18F/forest-service-prototype/issues/24#issuecomment-249953440,
or mute the thread

**Comment by fureigh** [comment]
Cool. If that's the case, this is covered by #11 and #2.
